### ISSUE TITLE
Decide on font(s)

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#11]
- Choose header and body font family. (On the About page it looks like we're not being consistent.)
- Once font has been chosen, make sure Main / About / Projects / Partners pages all use the right fonts. 
- FYI, the logo font is OpenSans + OpenSans-ExtraBold

**Comment by geckya** [comment]
The About page was the first one I did, and uses some extra tags - `title` and `teaser` - that were left blank on the other pages.  I'll change it to make it match the others, but am not assigning this task to myself because I'm not up for making overall font choices tonight.  If one of our design gurus wants to make some decisions, I can implement them.

**Comment by gati** [comment]
Whoa, a `teaser` tag! Web development has moved on since the last time I did this. :)

**Comment by geckya** [comment]
Haha! I lied about the `title` one, though - that's what I had used across the board; the "About" page was unique in using `teaser` and `subheading` as well.

**Comment by geckya** [comment]
Anyway, if we want to change font family, we'll just need to make one or two global CSS changes.

**Comment by gati** [comment]
Nice! Sounds like a plan. :)

**Comment by gati** [comment]
Closing this out as it's baked into the theme.
