### ISSUE TITLE
www.datafordemocracy.org returns 404

### ISSUE THREAD

**Issue by jimmycallin** [Data4Democracy/datafordemocracy.org#57]
Not sure this is the right place to post it since my guess is this is more of a domain configuration issue, but anyway:

www.* should probably redirect to the root website.

**Comment by thebouv** [comment]
Confirmed by doing digs on domain and the www host.  There is no host record for www set up right now.

Once someone does create the record to point to the same IP (if A record) or domain (if CNAME record), make sure on the hosting side that you make the appropriate changes there too.

For instance, if you want datafordemocracy.org to always be the destination, make sure the www host does a 301 permanent redirect to that domain.  Instead of just both working.  If you allow both to work and don't do the 301, Google sees it as two sites, duplicate content, and splits your SEO.

If I can help at all just let me know.

**Comment by geckya** [comment]
Calling @gati!
